// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeR4S16Q4m-J7X0pxWyLOZ1I8Z_KpU2DM',
    appId: '1:1027710391881:web:e4bffd1fbb39e050db5198',
    messagingSenderId: '1027710391881',
    projectId: 'smart-lamp-dcb5e',
    authDomain: 'smart-lamp-dcb5e.firebaseapp.com',
    storageBucket: 'smart-lamp-dcb5e.appspot.com',
    measurementId: 'G-MCZSLKH4V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOqiO9JgwqYZYg7RaOE9p2N-MUAXo9oKI',
    appId: '1:1027710391881:android:51e5891ee06b9954db5198',
    messagingSenderId: '1027710391881',
    projectId: 'smart-lamp-dcb5e',
    storageBucket: 'smart-lamp-dcb5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFMS73XflPk19DSOKBnBohYxW3wetfXY',
    appId: '1:1027710391881:ios:b64734f7b2ddd237db5198',
    messagingSenderId: '1027710391881',
    projectId: 'smart-lamp-dcb5e',
    storageBucket: 'smart-lamp-dcb5e.appspot.com',
    iosClientId: '1027710391881-p0485416qi0l4fagl5oab8hdfdgi5sp9.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOFMS73XflPk19DSOKBnBohYxW3wetfXY',
    appId: '1:1027710391881:ios:7d6da51875942b64db5198',
    messagingSenderId: '1027710391881',
    projectId: 'smart-lamp-dcb5e',
    storageBucket: 'smart-lamp-dcb5e.appspot.com',
    iosClientId: '1027710391881-vgrnlh30coropq4bhssdjnk7ddrgku4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartLamp.RunnerTests',
  );
}
